# Generated by Django 5.2 on 2025-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='polis_num',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
